bookwyrm_backend/src/main/java/com/bookwyrm/backend/book/controller/BookController.java, bookwyrm_backend/src/main/java/com/bookwyrm/backend/book/input/BookUploadInput.java, bookwyrm_backend/src/main/java/com/bookwyrm/backend/book/payload/BookUploadPayload.java, bookwyrm_backend/src/main/java/com/bookwyrm/backend/book/validator/BookUploadValidator.java
#47 Add endpoint for book upload, Add endpoint validation, Add response payload, Add upload input object.
Tested by running spring locally. 
In intellij, right click on BackendApplication::main and hit run.
Open postman or equivalent.
Hit the POST route `localhost:8080/api/book` with a json body as follows:
```
{
"name" : "book name",
"author" : "book author"
}
```
The response will come with an error list array that'll hold any resulting error messages, and the book title just to temporarily confirm that the route is accepting data properly.
=> #47 Add spring endpoint for uploading a book

bookwyrm_frontend/src/views/BookCreate.vue
Adds bound fields to the create screen. 
The screen will spit out an alert when pressing the submit button, and notify the user of what was submitted.
Eventually the alert will be replaced with an endpoint call.
=> #38 Add dummy functionality to upload book page.

bookwyrm_frontend/package-lock.json, bookwyrm_frontend/src/components/ReviewComponent.vue, bookwyrm_frontend/src/components/review_component.vue, bookwyrm_frontend/src/views/BookDetail.vue
Created vue component for displaying reviews
Note that this does not have any connection to the middleware and only loads reviews from hard coded test data
Closes #36
=> User/cameron jung/#36

bookwyrm_backend/build.gradle, bookwyrm_backend/src/main/java/com/bookwyrm/backend/BackendApplication.java, bookwyrm_backend/src/main/java/com/bookwyrm/backend/Comment.java, bookwyrm_backend/src/main/java/com/bookwyrm/backend/CommentRepository.java, bookwyrm_backend/src/main/resources/application.properties
Pull request for #16. Spring boot now can send and access data in MongoDB
=> User/long vu/#16

bookwyrm_frontend/src/services/ReviewService.js
gave it a postReview method.
Pretty sure I did it right but I don't really have a way to check that it works.
This Should close #39
=> Created ReviewService.js

bookwyrm_backend/src/main/java/com/bookwyrm/backend/book/controller/BookController.java, bookwyrm_backend/src/main/java/com/bookwyrm/backend/book/dao/BookDao.java, bookwyrm_backend/src/main/java/com/bookwyrm/backend/book/input/BookUploadInput.java, bookwyrm_backend/src/main/java/com/bookwyrm/backend/book/payload/BookUploadPayload.java, bookwyrm_backend/src/main/java/com/bookwyrm/backend/book/service/BookService.java, bookwyrm_backend/src/main/java/com/bookwyrm/backend/book/service/validator/BookValidator.java, bookwyrm_backend/src/test/java/com/bookwyrm/backend/integration/book/controller/BookControllerTests.java, bookwyrm_backend/src/test/java/com/bookwyrm/backend/unit/book/validator/BookValidatorTests.java, bookwyrm_backend/src/test/java/com/bookwyrm/backend/unit/comment/validator/CommentValidatorTests.java
Closes #58
Review list in Dao will have to wait until reviews get their own dao
=> #58 Add persistance for books, Update controller tests

bookwyrm_frontend/src/services/CommentService.js
=> Added service for comments

bookwyrm_frontend/src/services/BookService.js
=> #66 Add service for searching a book.

bookwyrm_backend/src/main/java/com/bookwyrm/backend/book/controller/BookController.java, bookwyrm_frontend/src/components/BookBriefView.vue, bookwyrm_frontend/src/components/SearchBar.vue, bookwyrm_frontend/src/router/index.js, bookwyrm_frontend/src/views/BookSearch.vue
=> #96 Add view for brief search results

bookwyrm_backend/src/main/java/com/bookwyrm/backend/book/controller/BookController.java, bookwyrm_backend/src/main/java/com/bookwyrm/backend/book/validator/BookValidator.java, bookwyrm_backend/src/main/java/com/bookwyrm/backend/comment/controller/CommentController.java, bookwyrm_backend/src/main/java/com/bookwyrm/backend/comment/dao/CommentDao.java, bookwyrm_backend/src/main/java/com/bookwyrm/backend/comment/dao/CommentService.java, bookwyrm_backend/src/main/java/com/bookwyrm/backend/review/controller/ReviewController.java, bookwyrm_backend/src/main/java/com/bookwyrm/backend/review/dao/ReviewDao.java, bookwyrm_backend/src/main/java/com/bookwyrm/backend/review/input/ReviewUploadInput.java, bookwyrm_backend/src/test/java/com/bookwyrm/backend/integration/comment/controller/CommentControllerTests.java, bookwyrm_backend/src/test/java/com/bookwyrm/backend/unit/book/validator/BookValidatorTests.java
ReviewDao is updated to accommodate comments.
Need some adjustments and testing for Comment resistance.
=> Comment resistance

bookwyrm_frontend/package-lock.json, bookwyrm_frontend/package.json, bookwyrm_frontend/src/App.vue, bookwyrm_frontend/src/components/CommentComponent.vue, bookwyrm_frontend/src/components/RatingComponent.vue, bookwyrm_frontend/src/components/ReviewComponent.vue, bookwyrm_frontend/src/components/StarRatingWrapperComponent.vue, bookwyrm_frontend/src/views/BookDetail.vue
Added the components "RatingsComponent" and "StarRatingsWrapperComponent"
- The Ratings Component is capable of being in displayOnly mode which can be used to output ratings to be viewed.
-- When not in displayOnly mode the ratings component can be edited, allowing the user to add ratings and select a specific genre for the rating. Ratings can also be removed by pressing an "X" button.
- The StarRatingsWrapperComponent is used to hold an ID so that individual ratings can be distinguished
-- it holds the "vue-star-rating" component which is not my own work, it can be installed using npm and is distributed under the rather generous MIT license. Further information can be found at the github repository here: https://github.com/craigh411/vue-star-rating
- This should close issue #123 
- Thus …
=> User/cameron jung/#123

bookwyrm_backend/src/main/java/com/bookwyrm/backend/comment/controller/CommentController.java, bookwyrm_backend/src/main/java/com/bookwyrm/backend/review/controller/ReviewController.java, bookwyrm_frontend/src/components/ReviewComponent.vue, bookwyrm_frontend/src/views/BookDetail.vue
Update username at endpoint when anonymous.
closes #144
=> #144 Add anonymous flag element.

bookwyrm_frontend/src/components/ReviewComponent.vue, bookwyrm_frontend/tests/unit/components/ReviewComponent.spec.js
The ratings component will no longer appear in the review creator if the user isn't logged in. Instead large red text that reads: You must log in to add star ratings to your review", will appear in place of the ratings component.
closes #132
=> User/cameron jung/#132

bookwyrm_backend/src/main/java/com/bookwyrm/backend/user/controller/UserController.java, bookwyrm_backend/src/main/java/com/bookwyrm/backend/user/input/UserAuthInput.java, bookwyrm_backend/src/main/java/com/bookwyrm/backend/user/input/UserUpdateInput.java, bookwyrm_backend/src/main/java/com/bookwyrm/backend/user/payload/UserPayload.java, bookwyrm_backend/src/main/java/com/bookwyrm/backend/user/validator/UserValidator.java, bookwyrm_backend/src/test/java/com/bookwyrm/backend/unit/user/controller/UserControllerTests.java, bookwyrm_backend/src/test/java/com/bookwyrm/backend/unit/user/validator/UserUpdateValidatorTests.java, bookwyrm_backend/src/test/java/com/bookwyrm/backend/unit/user/validator/UserValidatorTests.java, bookwyrm_frontend/src/App.vue, bookwyrm_frontend/src/components/SearchBar.vue, bookwyrm_frontend/src/components/userComponent.vue, bookwyrm_frontend/src/main.js, bookwyrm_frontend/src/router/index.js, bookwyrm_frontend/src/services/UserService.js, bookwyrm_frontend/src/views/BookSearch.vue, bookwyrm_frontend/src/views/LoginScreen.vue, bookwyrm_frontend/src/views/UserDetailsScreen.vue
Add endpoint for role updating
Update login endpoint to return user info
Add input for role updating
Update tests
Add tests
Add screen for updating role info
Update front end storage to store role info
Probably should have done this in many smaller commits, sorry for the inconvenience. 
Resolves #136
=> #136 Add roles to DB

bookwyrm_frontend/src/components/CommentComponent.vue, bookwyrm_frontend/src/components/RatingComponent.vue, bookwyrm_frontend/src/components/ReviewComponent.vue, bookwyrm_frontend/src/components/StarRatingWrapperComponent.vue, bookwyrm_frontend/tests/unit/components/CommentComponent.spec.js, bookwyrm_frontend/tests/unit/components/RatingComponent.spec.js, bookwyrm_frontend/tests/unit/components/StarRatingWrapperComponent.spec.js
- Created test for RatingComponent.cue
- Created test for StarRatingWrapperComponent.vue
- fixed issue that caused test for CommentComponent to fail unless it
had an empty <div> tag
- removed empty div tag from CommentComponent.vue
- added name to StarRatingWrapperComponent.vue
closes #169
=> User/cameron jung/#169

bookwyrm_backend/src/main/java/com/bookwyrm/backend/review/controller/ReviewController.java, bookwyrm_backend/src/main/java/com/bookwyrm/backend/review/dao/ReviewDao.java, bookwyrm_backend/src/main/java/com/bookwyrm/backend/review/input/ReviewUploadInput.java, bookwyrm_backend/src/main/java/com/bookwyrm/backend/review/validator/ReviewValidator.java, bookwyrm_backend/src/test/java/com/bookwyrm/backend/unit/comment/controller/CommentControllerTests.java, bookwyrm_backend/src/test/java/com/bookwyrm/backend/unit/review/controller/ReviewControllerTests.java, bookwyrm_backend/src/test/java/com/bookwyrm/backend/unit/review/validator/ReviewValidatorTests.java
Once again,
#125: Review can handle ratings
#126: Rating data is stored in DB now
Update validators and Tests accordingly
=> Review endpoint now can accept ratings

bookwyrm_backend/src/main/java/com/bookwyrm/backend/book/controller/BookController.java, bookwyrm_backend/src/main/java/com/bookwyrm/backend/book/dao/BookDao.java, bookwyrm_backend/src/main/java/com/bookwyrm/backend/book/input/BookUpdateInput.java, bookwyrm_backend/src/main/java/com/bookwyrm/backend/book/validator/BookValidator.java, bookwyrm_backend/src/main/java/com/bookwyrm/backend/review/controller/ReviewController.java, bookwyrm_backend/src/test/java/com/bookwyrm/backend/unit/book/controller/BookControllerTests.java, bookwyrm_backend/src/test/java/com/bookwyrm/backend/unit/book/validator/BookValidatorTests.java
#129 
#130 
Books will compute average ratings and stored updated data in DB whenever a review is posted.
=> Books can accept ratings and stored ratings in DB

bookwyrm_backend/src/main/java/com/bookwyrm/backend/book/dao/BookDao.java
As discussed in the group forum, all genre scores, even 0 (when genre is not rated), will be sent to the backend. This commit lets books create all genres at creation and assign a score of 0 as default.
=> All rating values including 0 will be added

bookwyrm_backend/src/main/java/com/bookwyrm/backend/book/dao/BookDao.java, bookwyrm_backend/src/main/java/com/bookwyrm/backend/book/validator/BookValidator.java, bookwyrm_backend/src/main/java/com/bookwyrm/backend/user/controller/UserController.java, bookwyrm_backend/src/main/java/com/bookwyrm/backend/user/dao/UserDao.java, bookwyrm_backend/src/test/java/com/bookwyrm/backend/unit/book/validator/BookValidatorTests.java, bookwyrm_frontend/src/services/UserService.js
=> #186 Fix bug that caused roles to not work as intended

bookwyrm_frontend/src/components/ReviewComponent.vue, bookwyrm_frontend/src/views/BookDetail.vue
- average ratings now display
- ratings from reviews now display in focus mode
closes #160
=> #160 book ratings are now displayed

bookwyrm_frontend/src/main.js, bookwyrm_frontend/src/views/UserDetailsScreen.vue
=> #194 make names empty on new user creation

bookwyrm_backend/src/main/java/com/bookwyrm/backend/book/controller/BookController.java, bookwyrm_backend/src/main/java/com/bookwyrm/backend/book/dao/BookDao.java, bookwyrm_backend/src/main/java/com/bookwyrm/backend/book/input/BookUploadInput.java, bookwyrm_backend/src/test/java/com/bookwyrm/backend/unit/book/controller/BookControllerTests.java, bookwyrm_backend/src/test/java/com/bookwyrm/backend/unit/review/controller/ReviewControllerTests.java, bookwyrm_frontend/src/services/BookService.js, bookwyrm_frontend/src/views/BookCreate.vue
=> #199 Add genre selection to book creation screen

bookwyrm_backend/src/main/java/com/bookwyrm/backend/book/service/BookService.java
=> #207 Update search to be partial and case insensitive

bookwyrm_backend/src/main/java/com/bookwyrm/backend/book/dao/BookDao.java
=> #213 Add creation date to books in DB

bookwyrm_frontend/src/views/UserDetailsScreen.vue
Closes #197 
This is only a phony submission form given that we don't have systems in place to support an admin to validate it.
I think this should be enough, though I'm open to other opinions.
=> #197 Add phony photo Id submission form.

bookwyrm_frontend/src/components/RatingComponent.vue
=> #193 Hide rating component if only for display and empty.

bookwyrm_backend/src/main/java/com/bookwyrm/backend/book/controller/BookController.java, bookwyrm_backend/src/test/java/com/bookwyrm/backend/unit/book/controller/BookControllerTests.java
=> #215 Add endpoint to find the top book in a genre.

.github/workflows/codeql.yml
This is mostly autogenerated, and I haven't had an opportunity to test it because my choices were making a pull request or committing untested code directly to main. So, I would call this PR premature, I expect I will need to make revisions for code review.
- That being said once complete this closes #203
=> #203 Created codeql.yml

bookwyrm_frontend/src/views/BookSearch.vue
- Made it so that if booklist is empty than it won't try to render books
- Instead in such a case a box will appear
- said box eexplains that no book was found
- it also suggests that the user check their spelling or add the book
themselves
- closes #195
=> #195 search now indicate if a book wasn't found

bookwyrm_backend/src/main/java/com/bookwyrm/backend/book/controller/BookController.java, bookwyrm_backend/src/test/java/com/bookwyrm/backend/integration/book/controller/BookControllerTests.java, bookwyrm_backend/src/test/java/com/bookwyrm/backend/integration/comment/controller/CommentControllerTests.java, bookwyrm_backend/src/test/java/com/bookwyrm/backend/integration/review/controller/ReviewControllerTests.java, bookwyrm_backend/src/test/java/com/bookwyrm/backend/integration/user/controller/UserControllerTests.java
=> #214 Update test location

bookwyrm_frontend/src/views/BookSearch.vue
=> #196 Fix search page not reloading on re-search

bookwyrm_tests/BookWyrm_Load_Test.jmx
=> Update Load tests
